require File.expand_path('../lib/global_constants', __FILE__)
require File.expand_path('../lib/entity', __FILE__)
require File.expand_path('../lib/point', __FILE__)
require File.expand_path('../lib/line', __FILE__)
require File.expand_path('../lib/circle', __FILE__)
require File.expand_path('../lib/line_segment', __FILE__)
require File.expand_path('../lib/layout', __FILE__)
require File.expand_path('../lib/task', __FILE__)
